config/routes.rb
DW3::Application.routes.draw do
  
  resources :recipes

  resources :dworlds

  get "dworld/home"
  get "dworld/about"
  get "dworld/portfolio"
  get "dworld/news"
  get "dworld/contact"
  post "dworld/contact"
  get "dworld/index"

  root 'dworld#home'

end

app/models/dworld.rb
class Dworld < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dworld_controller.rb
class DworldController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end

  def news
  end

  def contact
    @name = params[:Name]
    @email = params[:"Email Address"]
    @question = params[:Questions]
    
    if params[:commit]
      flash.now[:error] = ""
      if @name.nil? || @name.empty?
        flash.now[:error] << "Please enter Name.</br>"
      end
      if @email.nil? || @email.empty?
        flash.now[:error] << "Please enter Email.</br>"
      end
    end
  end
end

app/controllers/dworlds_controller.rb
class DworldsController < ApplicationController
  before_action :set_dworld, only: [:show, :edit, :update, :destroy]

  # GET /dworlds
  # GET /dworlds.json
  def index
    @dworlds = Dworld.all
  end

  # GET /dworlds/1
  # GET /dworlds/1.json
  def show
  end

  # GET /dworlds/new
  def new
    @dworld = Dworld.new
  end

  # GET /dworlds/1/edit
  def edit
  end

  # POST /dworlds
  # POST /dworlds.json
  def create
    @dworld = Dworld.new(dworld_params)

    respond_to do |format|
      if @dworld.save
        format.html { redirect_to @dworld, notice: 'Info was successfully send to us.' }
        format.json { render action: 'show', status: :created, location: @dworld }
      else
        format.html { render action: 'new' }
        format.json { render json: @dworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dworlds/1
  # PATCH/PUT /dworlds/1.json
  def update
    respond_to do |format|
      if @dworld.update(dworld_params)
        format.html { redirect_to @dworld, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dworld.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dworlds/1
  # DELETE /dworlds/1.json
  def destroy
    @dworld.destroy
    respond_to do |format|
      format.html { redirect_to dworlds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dworld
      @dworld = Dworld.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dworld_params
      params.require(:dworld).permit(:name, :email, :question, :datesend)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def show_params
    html = "<div style='border:1px green solid; margin:10px;padding:10px;'>"
    html += '<heading><h2>Info Send to Us</heading><br/></h2>'
    
    params.each do |key, value|
      html += "<h3>#{key}: #{value} <br/></h3>" if (key != 'authenticity_token' && key != 'utf8')
      
  end
  html += '</div>'
  return html.html_safe
 end
 
 def things_to_do( links )
    # key = URL, value = body
    html = "<ul>"
    links.each do |url, body |
      html += "<li>" + link_to( body, url) + "</li>"
    end
    html +="</ul>"
    return html.html_safe

  end
end

app/helpers/dworld_helper.rb
module DworldHelper
end

app/helpers/dworlds_helper.rb
module DworldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dworld/Copy of home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DharmaWorld</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
  <!--nivo slider script-->
  
   <script type="text/javascript" src="/assets/jquery-2.0.2.js"></script>
   <script type="text/javascript" src="/assets/jquery.nivo.slider.js"></script>
  
  <!--slider script>
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
	<script src="javascripts/slides.min.jquery.js"></script>

	<script>
		$(function(){
			$('#slides').slides({
				preload: true,
				preloadImage: 'images/loading.gif',
				play: 5000,
				pause: 2500,
				hoverPause: true
			});
		});
	</script>
<!-->	
	
</head>
<body>

<!--start container-->
    <div id="container">

    <!--start header-->

    <header>
 
    <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dwlogo1b.png' %></a>    

	<!--end logo-->
	
   <!--start menu-->

	<nav>
    <ul>
    <li><a href="/dworld/home">Home</a></li>
    <li><a href="/dworld/about">About</a></li>
		<li><a href="/dworld/portfolio">Members</a></li>
    <li><a href="/dworld/news">News </a></li>
    <li><a href="/dworld/contact">Contact</a></li>

    </ul>
    </nav>
	<!--end menu-->
	
	<!--start nivo slider image-->
    <div id="wrapper">
        <a href="http://www.google.com" id="google" title="Go to google search">Temple Under Construction Photos</a>
        <div id="slider-wrapper">
            <div id="slider">
                <img src="/assets/toystory.jpg" title="toystory">
                <a href="http://www.google.com"><img src="/assets/up.jpg" title="This is an example of a caption" ></a>
                <img src="/assets/walle.jpg" title="walle">
                <img src="/assets/nemo.jpg" title="#htmlcaption" />
            </div>
            <div id="htmlcaption" class="nivo-html-caption">
                <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>. 
            </div>
        </div>
     </div>

    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>
    <!--end nivo slider-->
   
    <!--end header-->
	</header>

 
   
   <!--start holder-->
   <div class="holder_content1">
   
   <section class="group4">
   <h1>Latest news 最新消息</h1>
   <%= image_tag 'icon3.png'%>

   <article>
   <h2>1.08.2014  -  Recent Event</h2>

   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.   </p>

   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero. orem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero. orem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero. 
   </p>
   </article> 
   
   </section>

   </div>
   <!--end holder-->

   
   <!--start holder-->

   <div class="holder_content">

   <section class="group1">
   <h1>Event 典礼 </h1>
   <%= image_tag 'icon4.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   <a href=""><span class="button">Read more</span></a>
   </section>

   
   <section class="group2">
   <h1>Learning 慈心寺学院 </h1>
   <%= image_tag 'icon2.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   <a href=""><span class="button">Read more</span></a>
   </section>
   
   <section class="group3">
   <h1>Contributes 募集  及 捐赠</h1>
   <%= image_tag 'icon1.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.   </p>
   <a href=""><span class="button">Read more</span></a>
    
   </section>

 
   </div>
   <!--end holder-->
   
   
   </div>
   <!--end container-->
   
   <!--start footer-->
   <footer>
   <div class="container">
   <section class="footer_left">
   <h3>Contact information:
   <span>Dharma World Temple USA</span>
   <span>145-03 Bayside Avenue,</span>
   <span>Flushing, New York 11354</span>
   </h3>
   </section> 
   
   <section class="footer_left">
   <h3>Website:
   <span>www.dharmaworldus.org</span>
   <span></span>
   </h3>
   </section> 

   
   <aside class="footer_left">
   <h3>
   <span></span>
   <span></span>
   </h3>
   </aside> 
   <<%= image_tag 'm2a.png', size: '160x140'%>

    
   <div id="FooterTwo"> © Dharma World Temple USA </div>
   <div id="FooterTree"> Valid html5 / design and code by <a href="http://www.marijazaric.com">[KL] Hak.Aython</a> </div> 
   </div>
   </footer>
   <!--end footer-->
 <!-- Free template distributed by http://freehtml5templates.com -->  

<%= yield %>

</body>
</html>

app/views/dworld/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>About Us</title>
  <%= stylesheet_link_tag    "about", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %> 
  <%= csrf_meta_tags %>
  
  <!--nivo slider script-->
  
   <script type="text/javascript" src="/assets/jquery-2.0.2.js"></script>
   <script type="text/javascript" src="/assets/jquery.nivo.slider.js"></script>
  
</head>
<body>

<!--start container-->
    <div id="container">

    <!--start header-->

    <header>
 
    <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dwlogo1a.png' %></a>    

	<!--end logo-->
	
   <!--start menu-->

	<nav>
    <ul>
    <li><a href="/dworld/home">Home</a></li>
    <li><a href="/dworld/about">About</a></li>
		<li><a href="/dworld/portfolio">Members</a></li>
    <li><a href="/dworld/news">News </a></li>
    <li><a href="/dworlds/new">Contact</a></li>

    </ul>
    </nav>
	<!--end menu-->
	
	<!--start Video--------------------------------->
   <div class="holder_content2">
<iframe width="640" height="338" src="//www.youtube.com/embed/bbgHZWwyhcQ?rel=0&autoplay=1" frameborder="0" allowfullscreen></iframe>
    <!--end Video-->
   </div>
    <!--end header---------------------------------->
	</header>

  
   <!--start holder-->
   <div class="holder_content1">
   
   <section class="group4">
   <h1>About Dharma World Temple USA 关于我们</h1>
   <%= image_tag 'icon3.png'%>

   <article>
   <h2>1.08.2014  -  Recent Event</h2>

   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.   </p>

   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero. 
   </p>
   </article> 
   
   </section>

   </div>
   <!--end holder-->

   
   <!--start holder-->

   <div class="holder_content">

   <section class="group1">
   <h1>Temple </h1>
   <%= image_tag 'icon4.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   <a href=""><span class="button">Read more</span></a>
   </section>

   
   <section class="group2">
   <h1>Temple </h1>
   <%= image_tag 'icon2.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum  facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.</p>
   <a href=""><span class="button">Read more</span></a>
   </section>
   
   <section class="group3">
   <h1>Temple </h1>
   <%= image_tag 'icon1.png'%>
   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec molestie. Sed aliquam sem ut arcu. Phasellus sollicitudin. 
   Vestibulum condimentum facilisis nulla. In hac habitasse platea dictumst. Nulla nonummy. Cras quis libero.   </p>
   <a href=""><span class="button">Read more</span></a>
    
   </section>

 
   </div>
   <!--end holder-->
   
   
   </div>
   <!--end container-->
   
    <!--start footer-->
   <footer>
   <div class="container">
   <section class="footer_left">
   <h3>Contact information:
   <span>Dharma World Temple USA</span>
   <span>145-03 Bayside Avenue,</span>
   <span>Flushing, New York 11354</span>
   </h3>
   </section> 
   
   <section class="footer_left">
   <h3>Website:
   <span>www.dharmaworldus.org</span>
   <span></span>
   </h3>
   </section> 

   
   <aside class="footer_left">
   <h3>
   <span></span>
   <span></span>
   </h3>
   </aside> 
   <<%= image_tag 'm2a.png', size: '160x140'%>

    
   <div id="FooterTwo"> © Dharma World Temple USA </div>
   <div id="FooterTree"> Valid html5 / design and code by <a href="http://www.marijazaric.com">[KL] Hak.Aython</a> </div> 
   </div>
   </footer>
   <!--end footer-->
 <!-- Free template distributed by http://freehtml5templates.com -->  

<%= yield %>

</body>
</html>

app/views/dworld/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DharmaWorld</title>
  <%= stylesheet_link_tag    "contact", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--start container-->
    <div id="container">

    <!--start header-->

    <header>
 
    <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dwlogo1b.png'%></a>    

	<!--end logo-->
	
    <!--end header-->

	</header>



<% content_for :title do %>
	<% end %>

<%= form_tag do %>
	<table>
		<TR>
			<TD><h1></h1></TD>
		</TR>	<br/>
		
				<TR>
			<TD><h2>Contact Us with Questions Below</h2></TD>
		</TR><br/>	
		<TR>
			<TD><h3><%= label_tag "Your Name"%></h3></TD>
			<TD><h3><%= text_field_tag 'Name' %></h3></TD>
		</TR>
		<br/>
	
		<TR>
			<TD><h3><%= label_tag "Your Email Address"%></h3></TD>
			<TD><h3><%= email_field_tag 'Email Address' %></h3></TD>
		</TR>
		<br/>
		
		<TR>
			<TD><h3><%= label_tag "Your Question"%></h3></TD>
			<TD><h3><%= text_area_tag 'Question' %></h3></TD>
		</TR>
		<br/>
		
		<TR>
			<TD></TD>
			<TD><%= submit_tag 'Submit your question' %></TD>
		</TR>
		<br/>
	
		</table>
		<br/>	
		
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1510.8072723146244!2d-73.8223539243753!3d40.770501830958054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5f71fa637513012b!2sDharma+World!5e0!3m2!1sen!2sus!4v1395253333130" width="600" height="450" frameborder="0" style="border:0"></iframe>
		
<!--start menu-->

	<nav>
    <ul>
    <li><a href="/dworld/home">Home</a></li>
    <li><a href="/dworld/about">About</a></li>
		<li><a href="/dworld/portfolio">Members</a></li>
    <li><a href="/dworld/news">News</a></li>
    <li><a href="/dworlds/new">Contact</a></li>

    </ul>
    </nav>
<!--end menu-->

	
<% end %>
	
	<div style="border:0px black solid">
		<%#= "Name Submitted: " + @name %><br/>
		<%#= "Email Submitted: " + @email %><br/>
		<p></p>
		<%#= "We will get back to you ASAP. Thanks for your interest, " + @name + "." %><br/>
		<%#= params.inspect %>
		<p></p>
		</div>
<% if params[:commit] != nil %>
<%= show_params %>
<% end %>

   </div>
   <!--end container-->
      <!--start footer-->
   <footer>
   <div class="container">
   <section class="footer_left">
   <h3>Contact information:
   <span>Dharma World Temple USA</span>
   <span>145-03 Bayside Avenue,</span>
   <span>Flushing, New York 11354</span>
   </h3>
   </section> 
   
   <section class="footer_left">
   <h3>Website:
   <span>www.dharmaworldus.org</span>
   <span></span>
   </h3>
   </section> 

   
   <aside class="footer_left">
   <h3>
   <span></span>
   <span></span>
   </h3>
   </aside> 
   <<%= image_tag 'm2a.png', size: '160x140'%>

    
   <div id="FooterTwo"> © Dharma World Temple USA </div>
   <div id="FooterTree"> Valid html5 / design and code by <a href="http://www.marijazaric.com">[KL] Hak.Aython</a> </div> 
   </div>
   </footer>
   <!--end footer-->
   

app/views/dworlds/_form.html.erb
<%= form_for(@dworld) do |f| %>
  <% if @dworld.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dworld.errors.count, "error") %> prohibited this dworld from being saved:</h2>

      <ul>
      <% @dworld.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= f.label :name %> 名稱<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <h2><%= f.label :email %> 您的電郵<br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <h2><%= f.label :question %> 查問建議.<br>
    <%= f.text_area :question %></h2>
  </div>
  <div class="field">
    <%#= f.label :datesend %><br>
    <%#= f.datetime_select :datesend %>
  </div>
  <div class="actions">
    <%= f.submit "Send 遞交"%>
  </div>
<% end %>

app/views/dworlds/edit.html.erb
<h1>Editing dworld</h1>

<%= render 'form' %>

<%= link_to 'Show', @dworld %> |
<%= link_to 'Back', dworlds_path %>

app/views/dworlds/index.html.erb
<h1>Listing dworlds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Question</th>
      <th>Datesend</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dworlds.each do |dworld| %>
      <tr>
        <td><%= dworld.name %></td>
        <td><%= dworld.email %></td>
        <td><%= dworld.question %></td>
        <td><%= dworld.datesend %></td>
        <td><%= link_to 'Show', dworld %></td>
        <td><%= link_to 'Edit', edit_dworld_path(dworld) %></td>
        <td><%= button_to 'Destroy', dworld, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to Contact Page', new_dworld_path %>

app/views/dworlds/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DharmaWorld</title>
  <%= stylesheet_link_tag    "contact", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--start container-->
    <div id="container">

    <!--start header-->

    <header>
 
    <!--start logo-->
    <a href="#" id="logo"><%= image_tag 'dwlogo1b.png'%></a>    

	<!--end logo-->
	
    <!--end header-->

	</header>



<% content_for :title do %>
	<% end %>

<%= form_tag do %>
	<table>
		<TR>
			<TD><h1></h1></TD>
		</TR>	<br/>
		
				<TR>
			<TD><h2></h2></TD>
		</TR><br/>	
		<TR>
			<TD><h3>Contact Us with Questions Below
			</h3></TD>
			<TD><h3></h3></TD>
		</TR>
		<br/>
	

	
		</table>
		<br/>	
		
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1510.8072723146244!2d-73.8223539243753!3d40.770501830958054!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5f71fa637513012b!2sDharma+World!5e0!3m2!1sen!2sus!4v1395253333130" width="600" height="450" frameborder="0" style="border:0"></iframe>
		
<!--start menu-->

	<nav>
    <ul>
    <li><a href="/dworld/home">Home</a></li>
    <li><a href="/dworld/about">About</a></li>
		<li><a href="/dworld/portfolio">Members</a></li>
    <li><a href="/dworld/news">News</a></li>
    <li><a href="/dworld/contact">Contact</a></li>

    </ul>
    </nav>
<!--end menu-->

	
<% end %>
	
<%= render 'form' %>

   </div>
   <!--end container-->

<!--start footer-->
   <footer>
   <div class="container">
   <section class="footer_left">
   <h3>Contact information:
   <span>Dharma World Temple USA</span>
   <span>145-03 Bayside Avenue,</span>
   <span>Flushing, New York 11354</span>
   </h3>
   </section> 
   
   <section class="footer_left">
   <h3>Website:
   <span>www.dharmaworldus.org</span>
   <span></span>
   </h3>
   </section> 

   
   <aside class="footer_left">
   <h3>
   <span></span>
   <span></span>
   </h3>
   </aside> 
   <<%= image_tag 'm2a.png', size: '160x140'%>

    
   <div id="FooterTwo"> © Dharma World Temple USA </div>
   <div id="FooterTree"> Valid html5 / design and code by <a href="http://www.marijazaric.com">[KL] Hak.Aython</a> </div> 
          <li><a href="/dworlds">.</a></li>  
   </div>
   </footer>
   <!--end footer-->

				<%#= link_to 'Back', dworlds_path %>

app/views/dworlds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dworld.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dworld.email %>
</p>

<p>
  <strong>Question:</strong>
  <%= @dworld.question %>
</p>

<p>
  <strong>Datesend:</strong>
  <%= @dworld.datesend %>
</p>

<%#= link_to 'Edit', edit_dworld_path(@dworld) %> |
<%= link_to 'Return Home', dworld_home_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DharmaWorld</title>

</head>
<body>

<%= yield %>

</body>
</html>